version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    working_directory: ~/ev_station_finder_be
    docker:
      - image: circleci/ruby:2.5.3
        environment:
          PGHOST: localhost
          PGUSER: ev_station_finder_be
          RAILS_ENV: test
      - image: postgres:13.2
        environment:
          POSTGRES_USER: ev_station_finder_be
          POSTGRES_DB: ev_station_finder_be_test
          POSTGRES_PASSWORD:
    steps:
      - checkout
      - run: gem install bundler:2.2.23
      - run:
          name: ev_station_finder_be
          command: bundle -v
      - ruby/bundle-install

      - checkout
      - run: bundle config set --local path 'vendor/bundle'
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: bundle exec rake db:setup
      - run: bundle exec rspec
